### PR TITLE
feat(core): :sparkles: adding new props and varient

### PR DESCRIPTION
**Pull request by arkaprota**
## Description
varient props is added to verify listType is going to work or not

```
<CoreList varient="HTML" listType="AUTO">
      <CoreListItems>
              <CoreListItemsText primary="Enter your text"> 
      <CoreListItems>
<CoreList>

```
Ref: #284

### CODE REVIEW

**Review by techoneel — CHANGES_REQUESTED** [review]
Please change the props name because the **variant** prop is used by the mui library.

**Comment by arkaprota** [comment]
can you suggest me some name that can be used
@techoneel

**Comment by techoneel** [comment]
> can you suggest me some name that can be used
> @techoneel 

htmlVariant the value can be Boolean default false.

**Comment by anantakumarghosh** [comment]
After making changes, please re-request for review @arkaprota

**Comment by wrappidcare** [comment]
Merging since stale over 24hrs.

**Pull request merged**
